# Generated by Django 5.2.5 on 2025-09-08 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('profile_type', models.CharField(choices=[('VISITOR', 'Visitante'), ('STUDENT', 'Estudiante'), ('TEACHER', 'Docente'), ('PROFESSIONAL', 'Profesional'), ('GROUP_REPRESENTATIVE', 'Representante de Grupo')], default='VISITOR', max_length=30, verbose_name='Tipo de Perfil')),
                ('university', models.CharField(blank=True, max_length=255, null=True, verbose_name='Universidad')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Estudiante')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ocupación')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Empresa (Profesional)')),
                ('asistencia_confirmada', models.BooleanField(default=False, verbose_name='Asistencia Confirmada')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=300, verbose_name='URL del Logo')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Persona de Contacto')),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Persona de Contacto')),
                ('contact_person_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Persona de Contacto')),
                ('participation_options', models.JSONField(blank=True, null=True, verbose_name='Opciones de Participación')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_certificado', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('DISERTANTE', 'Disertante'), ('EMPRESA', 'Empresa')], max_length=10, verbose_name='Tipo de Certificado')),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='PDF Generado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Disertante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('bio', models.TextField(verbose_name='Biografía')),
                ('foto_url', models.CharField(blank=True, max_length=300, verbose_name='URL de la Foto')),
                ('tema_presentacion', models.CharField(max_length=255, verbose_name='Título de la Presentación')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Grupo')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MiembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_grupo', to='api.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Evento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('dia', models.DateField(verbose_name='Día del Evento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('aula', models.CharField(choices=[('Aula Magna', 'Aula Magna'), ('Aula 1', 'Aula 1'), ('Aula 2', 'Aula 2'), ('Aula 3', 'Aula 3'), ('Aula 4', 'Aula 4'), ('Aula 5', 'Aula 5'), ('Aula 6', 'Aula 6'), ('Aula 7', 'Aula 7'), ('Aula 8', 'Aula 8'), ('Aula 9', 'Aula 9'), ('Aula 10', 'Aula 10')], max_length=30, verbose_name='Aula')),
                ('disertante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disertante', verbose_name='Disertante')),
            ],
        ),
    ]
