# Generated by Django 5.2.5 on 2025-09-02 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('asistencia_confirmada', models.BooleanField(default=False, verbose_name='Asistencia Confirmada')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=300, verbose_name='URL del Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_certificado', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('DISERTANTE', 'Disertante'), ('EMPRESA', 'Empresa')], max_length=10, verbose_name='Tipo de Certificado')),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='PDF Generado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Disertante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('bio', models.TextField(verbose_name='Biografía')),
                ('foto_url', models.URLField(blank=True, max_length=300, verbose_name='URL de la Foto')),
                ('tema_presentacion', models.CharField(max_length=255, verbose_name='Título de la Presentación')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inscripcion', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('EMPRESA', 'Empresa'), ('GRUPO', 'Grupo')], default='INDIVIDUAL', max_length=10, verbose_name='Tipo de Inscripción')),
                ('nombre_grupo', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Grupo')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Evento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('dia', models.DateField(verbose_name='Día del Evento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('disertante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disertante', verbose_name='Disertante')),
            ],
        ),
    ]
