# Generated by Django 5.2.5 on 2025-09-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disertante',
            name='foto_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL de la Foto'),
        ),
    ]
