# Generated by Django 5.2.5 on 2025-08-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='certificado',
            name='pdf_generado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='PDF Generado'),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Imagen del Código QR'),
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Evento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('dia', models.DateField(verbose_name='Día del Evento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('disertante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disertante', verbose_name='Disertante')),
            ],
        ),
    ]
