# Generated by Django 5.2.5 on 2025-08-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nombre de la empresa si no está registrada en la base', max_length=255, null=True),
        ),
    ]
