# Generated by Django 5.2.5 on 2025-09-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_disertante_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='aula',
            field=models.CharField(choices=[('Aula Magna', 'Aula Magna'), ('Aula 1', 'Aula 1'), ('Aula 2', 'Aula 2'), ('Aula 3', 'Aula 3'), ('Aula 4', 'Aula 4'), ('Aula 5', 'Aula 5'), ('Aula 6', 'Aula 6'), ('Aula 7', 'Aula 7'), ('Aula 8', 'Aula 8'), ('Aula 9', 'Aula 9'), ('Aula 10', 'Aula 10')], default='Auditorio', max_length=30, verbose_name='Aula'),
            preserve_default=False,
        ),
    ]
