# Generated by Django 5.2.5 on 2025-10-25 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_configuracioncongreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='disertante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='api.disertante'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='asistente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='api.asistente'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asistente__isnull', False), ('disertante__isnull', True), ('empresa__isnull', True)), models.Q(('asistente__isnull', True), ('disertante__isnull', False), ('empresa__isnull', True)), models.Q(('asistente__isnull', True), ('disertante__isnull', True), ('empresa__isnull', False)), _connector='OR'), name='un_solo_destinatario_certificado'),
        ),
    ]
