# Generated by Django 5.2.5 on 2025-10-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_asistente_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='disertante',
        ),
        migrations.AddField(
            model_name='programa',
            name='disertantes',
            field=models.ManyToManyField(related_name='programas', to='api.disertante', verbose_name='Disertantes'),
        ),
    ]
