# Generated by Django 5.2.5 on 2025-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_programa_disertante_programa_disertantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disertante',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
    ]
